services:
    api:
        build:
            context: ./backend
            dockerfile: dockerfile.api
        image: ats-api
        volumes:
            - ./backend:/app
        ports:
            - '5000:5000'
        networks:
            - ats-network
    client:
        build:
            context: ./frontend
            dockerfile: dockerfile.client
        image: ats-client
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        networks:
            - ats-network
        environment:
            - CHOKIDAR_USEPOLLING=true

networks:
    ats-network:
        driver: bridge
