name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Write .env to backend/
        run: |
          echo "${{ secrets.ENV_FILE }}" > backend/.env

      - name: Write application.yml to backend/
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > backend/application.yml

      - name: Build API container
        run: |
          docker build -f backend/dockerfile.api -t backend-test-image backend/

      - name: Run tests inside container
        run: |
          docker run --rm -v ${{ github.workspace }}/test-results:/app/test-results backend-test-image /bin/bash -c "
            pip install pytest &&
            cd /app &&
            pytest -v -s --junitxml=/app/test-results/test-report.xml
          "

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
