name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build API container
        run: |
          docker build -f backend/dockerfile.api -t backend-test-image backend/

      - name: Run tests inside container
        run: |
          docker run --rm backend-test-image pytest test_app.py -v -s --junitxml=test-report.xml
