name: Run Pytest for test_app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pymongo flask requests
        pip install -r backend/requirements.txt

    - name: Run Pytest
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python -m pytest -v -s --junitxml=test-report.xml


    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: test-report.xml
